### ISSUE TITLE
Change code documentation for use of BOOST_FIXTURE_TEST_CASE

### ISSUE THREAD

**Issue by maxehrhardt** [rock-core/drivers-iodrivers_base#23]
https://github.com/rock-core/drivers-iodrivers_base/blob/07ef97922a2bf0c230ad3383c230998d12673d46/src/Fixture.hpp#L23-L29

2 Things in this comment should be changed to make the code work:

- `BOOST_FIXTURE_TEST` to `BOOST_FIXTURE_TEST_CASE`

- `MyDriver.openURI("test://")` to `driver.openURI("test://")`

**Comment by doudou** [comment]
Done. Thanks !
